### ISSUE TITLE
Issue in HomeFragment at  app/src/main/java/HomeFragment

### ISSUE THREAD

**Issue by santoshdvc** [santoshdvc/TheFive#2]
`

    protected void onNewIntent(Intent intent) {
        super.onNewIntent(intent);
        if (DataManager.getInstance().hasPermission(getContext())) {
            mSwipe.setEnabled(true);
            mSort.setVisibility(View.VISIBLE);
            mSwitch.setVisibility(View.GONE);
            initSpinner();
            initSort();
            process();
        }
    }
`

The code is at line number 218.  

Error Message : Cannot resolve method 'onNewIntent' in 'Fragment'

**Comment by Ehraz98** [comment]
@Override
protected void onNewIntent(Intent intent) {
    super.onNewIntent(intent);
    if (DataManager.getInstance().hasPermission(getContext())) {
        mSwipe.setEnabled(true);
        mSort.setVisibility(View.VISIBLE);
        mSwitch.setVisibility(View.GONE);
        initSpinner();
        initSort();
        process();
    }
}

Try this.
Attaching a reference that u can have a look on https://stackoverflow.com/questions/30043326/how-to-use-method-onnewintentintent-intent-inside-a-fragment

**Comment by santoshdvc** [comment]
> @override
> protected void onNewIntent(Intent intent) {
> super.onNewIntent(intent);
> if (DataManager.getInstance().hasPermission(getContext())) {
> mSwipe.setEnabled(true);
> mSort.setVisibility(View.VISIBLE);
> mSwitch.setVisibility(View.GONE);
> initSpinner();
> initSort();
> process();
> }
> }
> 
> Try this.
> Attaching a reference that u can have a look on https://stackoverflow.com/questions/30043326/how-to-use-method-onnewintentintent-intent-inside-a-fragment

Yeah. The second solution in stackoverflow looks perfect

**Comment by santoshdvc** [comment]
Done
